# Task 5 Modify Tuple indirectly
print("Enter 3 items for your shopping list")
slist1 = input("Item 1: ")
slist2 = input("Item 2: ")
slist3 = input("Item 3: ")
slist = (slist1, slist2, slist3)
shlist = list(slist)
print(shlist)
shlist.append("salt")
shlist.append("cheese")
print(shlist)
slist = tuple(shlist)
print(slist)
print(" | ".join(slist))